version: '3.8'
services:

  nginx:
    image: my-nginx-image #build your own image using the dockerfile
    volumes:
      - nginx.conf:/etc/nginx/nginx.conf
      - cert.pem:/etc/nginx/cert.pem
      - key.pem:/etc/nginx/key.pem
    ports:
      - "8443:8443/tcp"
      - "8443:8443/udp"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  quiche-client-data:
  quiche-server-data:
  grafana_data:
