FROM nginx:1.25.4

RUN apt-get update ; apt-get install lsb-release --no-install-recommends --no-install-suggests -y

RUN echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/mainline/debian `lsb_release -cs` nginx" | tee /etc/apt/sources.list.d/nginx.list

RUN apt-get update ; apt-get install nginx-module-otel --no-install-recommends --no-install-suggests -y

# COPY nginx.conf /etc/nginx/nginx.conf
# COPY cert.pem /etc/nginx/cert.pem
# COPY key.pem /etc/nginx/key.pem
